### ISSUE TITLE
error when trying to run

### ISSUE THREAD

**Issue by tttp** [majnu-campact/react-quickstart#1]
Thanks for sharing
Could you doc how to run? I'm trying 

    $nodejs ./src react-scripts start
    $nodejs ./src react-scripts build

but I get an error:
```
/var/www/react-quickstart/src/index.js:1
(function (exports, require, module, __filename, __dirname) { import 'bootstrap/dist/css/bootstrap.css'

``` 

I'm assuming I do not have the right node version or I'm not running it the right way. Could you clarify?

**Comment by majnu-campact** [comment]
It should work by just running 'npm start'. Does that not work?
I use node 6.

**Comment by majnu-campact** [comment]
I forgot to mention that you need to run `npm install`before that.

**Comment by tttp** [comment]
I did, and I might have a too old node (4.7.2)

Something I do not understand: why do we need node in the first place? I thought it would be all client side

**Comment by tttp** [comment]
works with node 8.
